// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJMZBp402fPeFhO_kyB83--jkHAIQqDQ',
    appId: '1:651032884341:web:dfdf449b7aac6cd7eaf43c',
    messagingSenderId: '651032884341',
    projectId: 'executive-function-5bcd9',
    authDomain: 'executive-function-5bcd9.firebaseapp.com',
    storageBucket: 'executive-function-5bcd9.firebasestorage.app',
    measurementId: 'G-QLVL437TFE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALqwoPVX_dj8UTm0rJh7Qqt-zLP5gFjGk',
    appId: '1:651032884341:ios:95bae6a1004727edeaf43c',
    messagingSenderId: '651032884341',
    projectId: 'executive-function-5bcd9',
    storageBucket: 'executive-function-5bcd9.firebasestorage.app',
    iosBundleId: 'com.example.executiveFunction',
  );
}
