import '../today/models/task_template.dart';

List<TaskTemplate> defaultTaskTemplates() {
  return const [
    TaskTemplate(
      id: 'shower',
      title: 'Shower',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.shower,
      isSystem: true,
      steps: [
        TaskTemplateStep(id: 'towel', label: 'Towel', isRequired: true),
        TaskTemplateStep(id: 'washcloth', label: 'Washcloth', isRequired: true),
        TaskTemplateStep(id: 'underwear', label: 'Underwear', isRequired: true),
        TaskTemplateStep(
          id: 'clothes',
          label: 'Clothes for day',
          isRequired: true,
        ),
        TaskTemplateStep(
          id: 'enter',
          label: 'Getting in shower',
          isRequired: true,
        ),
        TaskTemplateStep(id: 'hair', label: 'Washed hair'),
        TaskTemplateStep(id: 'shave', label: 'Shaved legs'),
      ],
    ),
    TaskTemplate(
      id: 'hair',
      title: 'Do Hair',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.hair,
      isSystem: true,
      steps: [
        TaskTemplateStep(id: 'brush', label: 'Brush hair', isRequired: true),
        TaskTemplateStep(id: 'style', label: 'Style hair', isRequired: true),
        TaskTemplateStep(
          id: 'products',
          label: 'Hair product',
          isRequired: true,
        ),
      ],
    ),
    TaskTemplate(
      id: 'teeth_morning',
      title: 'Brush Teeth',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.teeth,
      isSystem: true,
      steps: [
        TaskTemplateStep(
          id: 'brush_teeth_2min',
          label: 'Brush teeth for 2 minutes',
          isRequired: true,
        ),
        TaskTemplateStep(id: 'floss', label: 'Floss'),
        TaskTemplateStep(id: 'mouthwash', label: 'Use mouth wash'),
        TaskTemplateStep(
          id: 'gum_control_2min',
          label: 'Brush with gum control for 2 additional minutes',
        ),
      ],
    ),
    TaskTemplate(
      id: 'wash_face_morning',
      title: 'Wash Face',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.face,
      isSystem: true,
      steps: [
        TaskTemplateStep(
          id: 'washcloth',
          label: 'Get washcloth',
          isRequired: true,
        ),
        TaskTemplateStep(
          id: 'face_wash',
          label: 'Get face wash',
          isRequired: true,
        ),
        TaskTemplateStep(
          id: 'headband_wristbands',
          label: 'Get headband and wrist bands',
          isRequired: true,
        ),
        TaskTemplateStep(id: 'wash_face', label: 'Wash face', isRequired: true),
        TaskTemplateStep(id: 'dry_face', label: 'Dry face', isRequired: true),
        TaskTemplateStep(
          id: 'moisturizer',
          label: 'Moisturizer',
          isRequired: true,
        ),
      ],
    ),
    TaskTemplate(
      id: 'dressed',
      title: 'Get Dressed',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.dressed,
      isSystem: true,
      steps: [
        TaskTemplateStep(id: 'shirt', label: 'Shirt', isRequired: true),
        TaskTemplateStep(id: 'pants', label: 'Pants', isRequired: true),
        TaskTemplateStep(id: 'bra', label: 'Bra', isRequired: true),
        TaskTemplateStep(id: 'socks', label: 'Socks', isRequired: true),
        TaskTemplateStep(id: 'shoes', label: 'Shoes', isRequired: true),
      ],
    ),
    TaskTemplate(
      id: 'pack',
      title: 'Pack/Grab',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.pack,
      isSystem: true,
      steps: [
        TaskTemplateStep(id: 'lunchbox', label: 'Lunchbox', isRequired: true),
        TaskTemplateStep(id: 'snack', label: 'Snack', isRequired: true),
        TaskTemplateStep(id: 'water', label: 'Water', isRequired: true),
        TaskTemplateStep(id: 'computer', label: 'Computer', isRequired: true),
      ],
    ),
    TaskTemplate(
      id: 'meds',
      title: 'Meds',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.meds,
      isSystem: true,
      steps: [
        TaskTemplateStep(id: 'allieMeds', label: 'Allie', isRequired: true),
        TaskTemplateStep(id: 'fallonMeds', label: 'Fallon', isRequired: true),
      ],
    ),
    TaskTemplate(
      id: 'teeth_evening',
      title: 'Brush Teeth',
      phase: DayPhase.evening,
      type: TaskTemplateType.mustDoBlocking,
      icon: TaskIconKey.teeth,
      isSystem: true,
      steps: [
        TaskTemplateStep(
          id: 'brush_teeth_2min',
          label: 'Brush teeth for 2 minutes',
          isRequired: true,
        ),
        TaskTemplateStep(id: 'floss', label: 'Floss'),
        TaskTemplateStep(id: 'mouthwash', label: 'Use mouth wash'),
        TaskTemplateStep(
          id: 'gum_control_2min',
          label: 'Brush with gum control for 2 additional minutes',
        ),
      ],
    ),
    TaskTemplate(
      id: 'wash_face_evening',
      title: 'Wash Face',
      phase: DayPhase.evening,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.face,
      isSystem: true,
      steps: [
        TaskTemplateStep(
          id: 'washcloth',
          label: 'Get washcloth',
          isRequired: true,
        ),
        TaskTemplateStep(
          id: 'face_wash',
          label: 'Get face wash',
          isRequired: true,
        ),
        TaskTemplateStep(
          id: 'headband_wristbands',
          label: 'Get headband and wrist bands',
          isRequired: true,
        ),
        TaskTemplateStep(id: 'wash_face', label: 'Wash face', isRequired: true),
        TaskTemplateStep(id: 'dry_face', label: 'Dry face', isRequired: true),
        TaskTemplateStep(
          id: 'moisturizer',
          label: 'Moisturizer',
          isRequired: true,
        ),
      ],
    ),
    TaskTemplate(
      id: 'custom_morning_optional_lay_outfit',
      title: 'Lay out outfit',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.custom,
    ),
    TaskTemplate(
      id: 'custom_morning_optional_fill_water',
      title: 'Fill water bottle',
      phase: DayPhase.morning,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.custom,
    ),
    TaskTemplate(
      id: 'custom_morning_maydo_start_laundry',
      title: 'Start load of laundry',
      phase: DayPhase.care,
      type: TaskTemplateType.mayDo,
      icon: TaskIconKey.care,
    ),
    TaskTemplate(
      id: 'custom_morning_maydo_empty_dishwasher',
      title: 'Empty dishwasher',
      phase: DayPhase.care,
      type: TaskTemplateType.mayDo,
      icon: TaskIconKey.care,
    ),
    TaskTemplate(
      id: 'custom_afternoon_optional_refill_snacks',
      title: 'Refill snack bag',
      phase: DayPhase.afternoon,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.custom,
    ),
    TaskTemplate(
      id: 'custom_afternoon_maydo_counter_reset',
      title: 'Quick counter reset',
      phase: DayPhase.care,
      type: TaskTemplateType.mayDo,
      icon: TaskIconKey.care,
    ),
    TaskTemplate(
      id: 'custom_evening_optional_pack_tomorrow',
      title: 'Pack for tomorrow',
      phase: DayPhase.evening,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.pack,
    ),
    TaskTemplate(
      id: 'custom_evening_optional_set_clothes',
      title: 'Set out tomorrow clothes',
      phase: DayPhase.evening,
      type: TaskTemplateType.mustDoOptional,
      icon: TaskIconKey.dressed,
    ),
    TaskTemplate(
      id: 'custom_evening_maydo_load_dishwasher',
      title: 'Load dishwasher',
      phase: DayPhase.care,
      type: TaskTemplateType.mayDo,
      icon: TaskIconKey.care,
    ),
    TaskTemplate(
      id: 'custom_evening_maydo_tidy_bathroom',
      title: 'Bathroom tidy',
      phase: DayPhase.care,
      type: TaskTemplateType.mayDo,
      icon: TaskIconKey.care,
    ),
  ];
}
